name: Build

on: [push, pull_request]

jobs:
    test:
        name: Build
        runs-on: ubuntu-latest

        # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Skip Duplicate Actions
              uses: fkirc/skip-duplicate-actions@v3.4.0

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
