name: Test

on: [push, pull_request]

jobs:
    pre_job:
        continue-on-error: true
        runs-on: ubuntu-latest

        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}

        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@master

    test:
        needs: pre_job
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}

        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Skip Duplicate Actions
              uses: fkirc/skip-duplicate-actions@v3.4.0

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              env:
                  POESESSID: ${{ secrets.POESESSID }}
              run: env POESESSID=$POESESSID npm run test:ci
