name: Test

on: [push, pull_request]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Skip Duplicate Actions
              uses: fkirc/skip-duplicate-actions@v3.4.0

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              env:
                  POESESSID: ${{ secrets.POESESSID }}
              run: env POESESSID=$POESESSID npm run test:ci
